package phrase

// ProjectsQualityPerformanceScore200ResponseAnyOfData struct for ProjectsQualityPerformanceScore200ResponseAnyOfData
type ProjectsQualityPerformanceScore200ResponseAnyOfData struct {
	Translations []ProjectsQualityPerformanceScore200ResponseAnyOfDataTranslationsInner `json:"translations,omitempty"`
}
